# Generated by Django 4.0.4 on 2022-06-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='today_feeling',
            field=models.CharField(choices=[('행복', '행복'), ('아주좋음', '아주좋음'), ('좋음', '좋음'), ('그냥저냥', '그냥저냥'), ('우울', '우울'), ('슬픔', '슬픔'), ('나쁨', '나쁨'), ('최악', '최악'), ('편안한', '편안한')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='재완', max_length=50),
        ),
    ]
