# Generated by Django 4.0.4 on 2022-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
                ('writer', models.CharField(blank=True, default='재완', max_length=20, null=True)),
                ('feeling', models.CharField(choices=[('행복', '행복'), ('아주좋음', '아주좋음'), ('좋음', '좋음'), ('그냥저냥', '그냥저냥'), ('우울', '우울'), ('슬픔', '슬픔'), ('나쁨', '나쁨'), ('최악', '최악'), ('편안한', '편안한')], max_length=50, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
