# Generated by Django 4.0.4 on 2022-07-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feeling',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
