# Generated by Django 4.0.4 on 2022-07-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_blog_diary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='body',
            new_name='content',
        ),
    ]
