# Generated by Django 4.0.5 on 2022-07-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_body_diary_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='Post',
        ),
    ]
