# Generated by Django 4.0.4 on 2022-07-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_diary_image'),
        ('myapp', '0004_rename_diary_post'),
    ]

    operations = [
    ]
